### ISSUE TITLE
Modélisation front-end

### ISSUE THREAD

**Issue by ghost** [TSAP-Laval/consume-frontend#35]
J'ai parcouru l'ensemble des modèles définis dans le code front-end et j'ai l'impression qu'on pourrait vraimer améliorer la manière dont ils sont définis. Par example, nous avons 3 implémentations différentes d'un modèle de métrique selon le contexte. Selon moi, on devrait avoir deux types de modèle : un type qui représente une entitée de notre database et un type qui sert de conteneur pour un besoin spécifique dans une vue. 

Lorsque je parle d'un type de modèle "conteneur", je réfère à un modèle qui sert purement à contenir de l'information nécessaire à l'affichage. Par example, pour l'action map, on a une entité qui contient une liste de tous les types d'actions utilisés et les couleurs qui y sont associées. Pour tout ce qui est du reste (Player, Match, Team, Metric, etc.), on devrait avoir des modèles fixes et ne se servir que des attributs dont on à besoin.

Bien que loin que parfait, voici un aperçu de ce que pourrait avoir l'air l'ensemble des modèles de l'app:

//Database Models
export interface Season {
    start_year: number
    end_year: number
}

export interface Match {
    match_id: number
    home_team: Team
    away_team: Team
    date: Date
    location: String
}

export interface Team {
    team_id: number
    name: string
    season: Season
    players: Player[]
    metrics: Metric[]
}

export interface Player {
    player_id: number
    first_name: string
    last_name: string
}

export interface Context {
    team: Team
    match: Match
    player: Player
}

export interface Metric {
    metric_id: number;
    name: string;
    formula: number;
    deviation: number;
    team: Team
    last_match: Match;
}

export interface PlayerPosition {
    position_id: number
    name: string
    context: Context
}

export interface Coordinate {
    x: number
    y: number
}

export interface Action {
    action_id: string
    description: string
    start: Coordinate
    end: Coordinate
    is_positive: boolean
    context: Context
}

//View models
export interface ActionImpact {
    description: string
    is_positive: boolean
    used: boolean
}

export class ActionType {
    description: string
    color: RGBColor
    used: boolean
}

export class RGBColor {
    r: number
    g: number
    b: number
}

export interface Field {
    x_zones: number
    y_zones: number
    zones: Zone[]
}

export interface Zone {
    x_zone: number
    y_zone: number
    actions: Action[]
    percentage: number
    rating: number
}

**Comment by loicndjoyi** [comment]
Je suis du même avis par contre il faudra changer des trucs dans ta proposition. À certaines places on ne retourne pas nécessairement un objet du back-end. Exemple, pour les metrics de mon côté lastMatch représente la statistique du dernier match (La valeur en chiffre). Je serai partant pour m'y coller une fois que tout le monde aura donné son avis.
